### ISSUE TITLE
Python2.6-support is broken by .total_seconds() in utils.py

### ISSUE THREAD

**Issue by woutervh** [fafhrd91/pyramid_sockjs#1]
total_seconds() is new in python2.7

but is used in https://github.com/fafhrd91/pyramid_sockjs/blob/master/pyramid_sockjs/transports/utils.py#L53

> td365seconds = int(td365.total_seconds())

**Comment by rbhadauria0** [comment]
To sidestep potential financial dangers, steer clear. They relentlessly push for additional investments, citing market trends. When I refused and asked for my initial investment to be returned, they stopped communicating, and my money wasn't returned. I have evidence of blocked funds and communication, but oliviatrader 44 AT gmail  com was able to retrieve all my funds."



WhatsApp.  +---1 4----23 ----248 ---2140-
